// SPDX-License-Identifier: BSD-3-Clause

#include "osmem.h"

/* Global head of the Memory List */
block_meta_t *head = NULL;
size_t list_size = 0;

/* Global heap preallocation */
int prealloc_done = NOT_DONE;

// ---------- MAIN FUNCTIONS ----------

void *os_malloc(size_t size)
{
	/* If size is 0, return NULL and do nothing*/
	if (size == 0)
		return NULL;

	size_t raw_size = BLOCK_ALIGN + ALIGN(size);

	block_meta_t *new_block;
	if (raw_size <= MMAP_THRESHOLD && prealloc_done == NOT_DONE) {
		new_block = prealloc_heap();
		DIE(!new_block, "os_malloc: failed heap preallocation\n");

		add_block(new_block);
		if ((raw_size < MMAP_THRESHOLD) && (MMAP_THRESHOLD - raw_size >= MIN_SPACE)) {
			split_block(new_block, size);
		} else {
			new_block->status = STATUS_ALLOC;
		}
		
		/* Mark prealloc as done */
		prealloc_done = DONE;

		return get_address_by_block(new_block);
	}
	
	block_meta_t *free_block = reuse_block(size);
	if (free_block)
		return get_address_by_block(free_block);

	new_block = alloc_new_block(size, MMAP_THRESHOLD);
	DIE(!new_block, "os_malloc: failed allocation\n");

	add_block(new_block);


	return get_address_by_block(new_block);
}

void os_free(void *ptr)
{	
	/* If pointer is NULL, do nothing */
	if (ptr == NULL)
		return;
	
	block_meta_t *block = get_block_by_address(ptr);

	/* If the address was generated by mmap */
	if (block->status == STATUS_MAPPED) {
		extract_block(block);
		int ret = free_mmaped_block(block);
		DIE(ret, "os_free: munmap failure\n");
		return;
	}

	/* If the address was generated by sbrk */
	if (block->status == STATUS_ALLOC) {
		mark_freed(block);
		merge_free_blocks(block);
	}
}

void *os_calloc(size_t nmemb, size_t size)
{
	if (!size || !nmemb)
		return NULL;

	size_t raw_size = BLOCK_ALIGN + ALIGN(nmemb * size);

	block_meta_t *new_block;
	if (raw_size <= PAGE_SIZE && prealloc_done == NOT_DONE) {
		new_block = prealloc_heap();
		memset_block(new_block, 0);
		DIE(!new_block, "os_calloc: failed heap preallocation\n");

		add_block(new_block);
		if ((raw_size < PAGE_SIZE) && (PAGE_SIZE - raw_size >= MIN_SPACE)) {
			split_block(new_block, nmemb * size);
		} else {
			new_block->status = STATUS_ALLOC;
		}
		
		/* Mark prealloc as done */
		prealloc_done = DONE;

		return get_address_by_block(new_block);
	}
	
	block_meta_t *free_block = reuse_block(nmemb * size);
	if (free_block)
		return memset_block(free_block, 0);

	new_block = alloc_new_block(nmemb * size, PAGE_SIZE);
	DIE(!new_block, "os_calloc: failed allocation\n");

	memset_block(new_block, 0);
	add_block(new_block);

	return get_address_by_block(new_block);
}

void *os_realloc(void *ptr, size_t size)
{
	printf_("+++++++++++++++++++++++++++++++++\n");
	print_list();
	if (!ptr && !size)
		return NULL;

	if (!ptr) {
		block_meta_t *unused = reuse_block(size);
		if (unused)
			return get_address_by_block(unused);
		else
			return os_malloc(size);
	}

	if (!size) {
		os_free(ptr);
		return NULL;
	}

	block_meta_t *block = get_block_by_address(ptr);
	if (block->status == STATUS_FREE)
		return NULL;
	
	/* If the block was mapped is very simple, make a new block, copy the contents and
	delete the previous one */
	if (block->status == STATUS_MAPPED) {
		block_meta_t *new_block = realloc_mapped_block(block, size);
		DIE(!new_block, "os_realloc: failed allocation\n");
		return get_address_by_block(new_block);
	}

	/* If the size is smaller than block->size, there is a possibility that
	we have to split the block */
	size_t true_size = get_raw_size(block);
	if (ALIGN(size) < true_size) {
		if (true_size - ALIGN(size) >= MIN_SPACE) {
			block->size = true_size;
			split_block(block, size);
			return ptr;
		}
	}

	/* Check if it is the last block in Memory List; because there is a 
	possibility that it was previously truncated, we have to get it's real,
	allocated size */
	if (!block->next) {
		if (ALIGN(size) <= true_size) {
			block->size = size;
			return ptr;
		}

		/* Expand */
		expand_heap(ALIGN(size) - true_size);
		block->size = size;
		return ptr;
	}

	/* Check if it is possible to truncate / use the memory that was previously
	truncated, or expand the heap if it is the last block */
	void *ret_addr = truncate_block(block, size);
	if (ret_addr)
		return ret_addr;

	/* Search for free blocks to move the data */
	block_meta_t *unused = reuse_block(size);
	if (unused) {
		copy_contents(block, unused);
		os_free(ptr);
		return get_address_by_block(unused);
	}

	/* Try merging with free block  next to block */
	/* This is a fucking problem */
	block_meta_t *ret = make_space(block, size);
	if (ret)
		return get_address_by_block(ret);

	block_meta_t *new_block = alloc_new_block(size, MMAP_THRESHOLD);
	DIE(!new_block, "os_realloc: failed reallocation\n");

	add_block(new_block);
	copy_contents(block, new_block);
	os_free(ptr);

	return get_address_by_block(new_block);	
}
